### ISSUE TITLE
Updating client children status

### ISSUE THREAD

**Issue by Imagine3D-Ben** [RinsibleElk/Deadfile#14]
If you cancel or complete a job the clients tree on the right hand side doesn't update the job icon until you go to either Jobs or Invoice list

**Comment by RinsibleElk** [comment]
The worst of this is I think fixed by some other related issues. There's one thing I'd like to clean up at a later stage which is to look at keeping the browser and content in sync - for example, when the Back button is hit on the navigation bar, however this is quite a different issue, so I will close this one and create a new enhancement for that idea.
