### ISSUE TITLE
Tree refreshing

### ISSUE THREAD

**Issue by Imagine3D-Ben** [RinsibleElk/Deadfile#24]
Not a big issue.

I just tried to sync to check if this was already a thing but it failed to open so I assume you're in the middle of changing something. I just thought if I were to search for a client and then decide to choose show inactive can we make sure the tree refreshes immediately? Simply a 'fix' in case the user forgets to check include inactive first.

**Comment by RinsibleElk** [comment]
Not sure what you mean. If you hit include inactive it should already
immediately refresh the browser pane.

Try now. I don't tend to check in unless the thing at least runs, so in
theory the only errors you should get due to timing will be from the entity
framework model changing (it just changed by the way).

**Comment by Imagine3D-Ben** [comment]
Yeah it's fine it already does it
