### ISSUE TITLE
Mass adding data manually

### ISSUE THREAD

**Issue by Imagine3D-Ben** [RinsibleElk/Deadfile#25]
Is this the time to mass add data manually in the office? I added a few but if I were to add loads in to actually start using deadfile am I wasting my time? i.e. will it disappear?

**Comment by Imagine3D-Ben** [comment]
Or can we create a way where if I do we can create a file to import it again?

**Comment by RinsibleElk** [comment]
Right I've sort of planned how we're going to handle migrations in general. We do not want to be doing this regularly. Because we are going to be operating on a shared client database, without Visual Studio etc present, I have decided our best bet is that I will prepare migrations on my machine. When I deploy a new installer to you, I will provide a SQL script (generated by Entity Framework) that you should run in SQL Server Management Studio from your box, prior to launching the new installed version. I would like to test this procedure on Friday.

I do like the idea of an Export / Import page though. I think that could be quite sweet. We should plan to make as much progress as we can before the new year so that I can come into the office and fix anything I completely balls up. Not that I'm any good at SQL but hey.

**Comment by RinsibleElk** [comment]
OK, I have added the ability to import/export the entire database from/to JSON - pretty savage, but might get us out of trouble in the early days while we're testing stuff. There's a pathetic effort at versioning the serialized data in there, which you know might work, or might not. Ultimately, it's just text, so worst comes to worst I'll be able to hack it around in a script and drop box it to you if I screw stuff up. We shouldn't use this after like the first couple of weeks, we'll use database backups obvs. I'll be in on Friday all day to get us set up and maybe another day before the new year too.
